base/urls.py
from django.urls import path

from .views import TaskList, TaskDetail, TaskCreate, TaskUpdate, TaskDelete, UserLogin, UserLogout, UserRegistration


app_name = 'base'
urlpatterns = [
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', UserLogout.as_view(), name='logout'),
    path('registration/', UserRegistration.as_view(), name='registration'),

    path('', TaskList.as_view(), name='tasks'),
    path('task/<int:pk>/', TaskDetail.as_view(), name='task'),

    path('create/', TaskCreate.as_view(), name='create'),
    path('update/<int:pk>/', TaskUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', TaskDelete.as_view(), name='delete'),
]

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

handler404 = 'base.views.page_not_find_view'

base/models.py
from django.db import models
from django.contrib.auth.models import User


class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=50)
    description = models.TextField(max_length=1350, null=True, blank=True)
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title', 'complete', 'created']

base/views.py
from django.conf import settings
from django.urls import reverse_lazy
from django.contrib.auth import login
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView

from .models import Task


class CustomLoginRequiredMixin(LoginRequiredMixin):
    redirect_field_name = settings.REDIRECT_FIELD_NAME


class TaskList(CustomLoginRequiredMixin, ListView):
    model = Task
    context_object_name = 'tasks'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = context['tasks'].filter(user=self.request.user)
        search = self.request.GET.get('search') or ''

        if search:
            context['tasks'] = context['tasks'].filter(title__icontains=search)

        context['search'] = search

        return context


class TaskDetail(LoginRequiredMixin, DetailView):
    model = Task
    context_object_name = 'task'

    def dispatch(self, request, *args, **kwargs):
        task = self.get_object()

        return (
            render(request, 'base/403.html')
            if task.user != self.request.user
            else super(TaskDetail, self).dispatch(request, *args, **kwargs)
        )


class TaskCreate(CustomLoginRequiredMixin, CreateView):
    model = Task
    template_name = 'base/task_create.html'
    fields = ['title', 'description']
    success_url = reverse_lazy('base:tasks')

    def form_valid(self, form):
        form.instance.user = self.request.user

        return super(TaskCreate, self).form_valid(form)


class TaskUpdate(CustomLoginRequiredMixin, UpdateView):
    model = Task
    template_name = 'base/task_update.html'
    fields = ['title', 'description', 'complete']

    def form_valid(self, form):
        form.instance.user = self.request.user

        return super(TaskUpdate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('base:task', kwargs={'pk': self.object.pk})

    def dispatch(self, request, *args, **kwargs):
        task = self.get_object()

        if task.user != self.request.user:
            return render(request, 'base/403.html')

        return super(TaskUpdate, self).dispatch(request, *args, **kwargs)


class TaskDelete(CustomLoginRequiredMixin, DeleteView):
    model = Task
    template_name = 'base/task_delete.html'
    context_object_name = 'task'
    success_url = reverse_lazy('base:tasks')

    def dispatch(self, request, *args, **kwargs):
        task = self.get_object()

        if task.user != self.request.user:
            return render(request, 'base/403.html')

        return super(TaskDelete, self).dispatch(request, *args, **kwargs)


class UserLogin(LoginView):
    template_name = 'base/login.html'
    fields = '__all__'
    redirect_authenticated_user = True


class UserLogout(LogoutView):
    next_page = 'base:login'
    template_name = 'base/logout.html'


class UserRegistration(FormView):
    template_name = 'base/registration.html'
    form_class = UserCreationForm
    success_url = 'base:tasks'

    def form_valid(self, form):
        user = form.save()

        if user is not None:
            login(self.request, user)

        return super(UserRegistration, self).form_valid(form)

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('base:tasks')

        return super(UserRegistration, self).get(request, *args, **kwargs)


def page_not_find_view(request, exception):
    return render(request, 'base/404.html', status=404)

base/templates/base.html
{% load i18n static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'base/css/style.css' %}" type="text/css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    </head>
    <body>
        <div class="container">
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

base/templates/base/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <div class="container__form-auth">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_div }}
            <input type="submit" value="Log in">
        </form>

        <p class="container__auth-link">
            You don't have any account? Not a problem!
            <a href="{% url 'base:registration' %}">Click on this link and go to Registration page!</a>
        </p>
    </div>
{% endblock %}

base/templates/base/logout.html
{% extends 'base.html' %}

{% block title %}Logout{% endblock %}

{% block content %}
    <div class="container__form-auth">
        <h2>Now you're logged out from your account.</h2>

        <p>
            <a class="container__redirect-link" href="{% url 'base:login' %}">Click this text to go to Login page.</a>
        </p>
    </div>
{% endblock %}

base/templates/base/registration.html
{% extends 'base.html' %}

{% block title %}Registration{% endblock %}

{% block content %}
    <div class="container__form-auth">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_div }}
            <input type="submit" value="Sign Up">
        </form>

        <p class="container__auth-link">
            You already have an account?
            <a href="{% url 'base:login' %}">Click on this link and go to Login page!</a>
        </p>
    </div>
{% endblock %}

base/templates/base/task_create.html
{% extends 'base.html' %}

{% block title %}Create Task{% endblock %}

{% block content %}
    <form method="POST" class="container__form-operation">
        {% csrf_token %}
        {{ form.as_div }}
        <input type="submit" value="submit">
    </form>

    <div class="container__back-to-main-page">
        <a href="{% url 'base:tasks' %}">
            <i class="bi bi-arrow-left"> Main page</i>
        </a>
    </div>
{% endblock %}

base/templates/base/task_delete.html
{% extends 'base.html' %}

{% block title %}Delete Task: {{ task.title }}{% endblock %}

{% block content %}
    <form method="POST" class="container__form-task-delete">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ task.title }}" Task?</p>
        <input type="submit" value="submit">
    </form>

    <div class="container__back-to-main-page">
        <a href="{% url 'base:tasks' %}">
            <i class="bi bi-arrow-left"> Main page</i>
        </a>
    </div>
{% endblock %}

base/templates/base/task_detail.html
{% extends 'base.html' %}

{% block title %}{{ task.title }}{% endblock %}

{% block content %}
    <div class="container__task-detail">
        <div class="container__title-header">
            <div class="container__title">
                <h1>{{ task.title }}</h1>
                {% if task.complete %}
                    <i class="bi bi-check"></i>
                {% endif %}
            </div>
            <div class="container__task-operations">
                <a href="{% url 'base:update' task.id %}" class="container__task-operation update"><i class="bi bi-pencil-fill"></i></a>
                <a href="{% url 'base:delete' task.id %}" class="container__task-operation delete"><i class="bi bi-x-lg"></i></a>
            </div>
        </div>
        <div class="container__information">
            <p class="container__task-description">{{ task.description }}</p>
            <div class="container__task-created-by">
                <p class="container__task-user">By {{ task.user }}</p>
                <p class="container__task-date">{{ task.created }}</p>
            </div>
        </div>
        <div class="container__back-to-main-page">
            <a href="{% url 'base:tasks' %}">
                <i class="bi bi-arrow-left"> Main page</i>
            </a>
        </div>
    </div>
{% endblock %}

base/templates/base/task_list.html
{% extends 'base.html' %}

{% block title %}TODO list page{% endblock %}

{% block content %}
    <div class="container__header">
        <div class="container__greetings">
            <h1>Greetings, {{ request.user }}!</h1>
            <a class="container__logout" href="{% url 'base:logout' %}">Wanna <b>Logout</b>?</a>
        </div>

        <div class="container__wrapper">
            <div class="container__search">
                <form method="GET" class="container__search-form">
                    <input type="text" name="search" value="{{ search }}" class="container__search-input">
                    <button type="submit" class="container__search-submit">
                        <i class="bi bi-search"></i>
                    </button>
                </form>
            </div>
            <div class="container__create-task">
                <a href="{% url 'base:create' %}" class="container__create-link create">
                    <i class="bi bi-plus-lg"></i>
                </a>
            </div>
        </div>
    </div>

    <div class="container__task-list">
        {% for task in tasks %}
            <div class="container__task-item">
                <div class="container__task-title">
                    <a
                        href="{% url 'base:task' task.id %}"
                        class="
                            container__task-link view
                            {% if task.complete %}
                                done
                            {% endif %}
                        "
                    >{{ task.title }}</a>
                </div>

                <div class="container__task-operations">
                    <a href="{% url 'base:update' task.id %}" class="container__task-operation update"><i class="bi bi-pencil-fill"></i></a>
                    <a href="{% url 'base:delete' task.id %}" class="container__task-operation delete"><i class="bi bi-x-lg"></i></a>
                </div>
            </div>
        {% empty %}
            <p>Tasks do not exist.</p>
        {% endfor %}
    </div>
{% endblock %}

base/templates/base/task_update.html
{% extends 'base.html' %}

{% block title %}Update Task: {{ task.title }}{% endblock %}

{% block content %}
    <form method="POST" class="container__form-operation">
        {% csrf_token %}
        {{ form.as_div }}
        <input type="submit" value="submit">
    </form>


    <div class="container__back-to-task">
        <a href="{% url 'base:task' task.id %}">
            <i class="bi bi-arrow-return-left"> Task: {{ task.title }}</i>
        </a>
    </div>
    <div class="container__back-to-main-page">
        <a href="{% url 'base:tasks' %}">
            <i class="bi bi-arrow-left"> Main page</i>
        </a>
    </div>
{% endblock %}